services:
  api-gateway:
    build: ../api-gateway
    container_name: api-gateway
    ports:
      - "8083:8080"
    networks:
      - backend
    depends_on:
      - auth-service
      - user-service
      - order-service
      - payment-service

  payment-service:
    build: ../payment-service
    ports:
      - "8084:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@payment-mongo:27017/paymentdb?authSource=admin
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.yaml
      SPRING_KAFKA_BOOTSTRAP_SERVERS: payment-kafka:9092
    depends_on:
      - payment-kafka
      - payment-mongo
    networks:
      - backend

  payment-mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: paymentdb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - payment-mongodata:/data/db
    networks:
      - backend

  payment-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 5s
      retries: 10

  payment-kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    depends_on:
      payment-zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: payment-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://payment-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  auth-service:
    build: ../authentication-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: auth_pass
      REDIS_HOST: redis
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - auth-postgres
      - redis
    networks:
      - backend

  user-service:
    build: ../user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: user_pass
    depends_on:
      - user-postgres
    networks:
      - backend

  order-service:
    build: ../order-service
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: order_pass
    depends_on:
      - order-postgres
    networks:
      - backend

  auth-postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth_pass
    volumes:
      - auth-pgdata:/var/lib/postgresql/data
#      - ./seed-admin.sql:/docker-entrypoint-initdb.d/seed-admin.sql
    networks:
      - backend

  user-postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user_pass
    volumes:
      - user-pgdata:/var/lib/postgresql/data
    networks:
      - backend

  order-postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: order_pass
    volumes:
      - order-pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  auth-pgdata:
  user-pgdata:
  order-pgdata:
  payment-mongodata:

networks:
  backend:
    driver: bridge