server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: auth-service
            uri: http://auth-service:8081
            predicates:
            - Path=/auth/**

          - id: user-service
            uri: http://user-service:8080
            predicates:
            - Path=/api/user/**
            - Path=/api/card/**

          - id: order-service
            uri: http://order-service:8081
            predicates:
              - Path=/api/orders/**